name: Build SQL project with code analysis

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.sql'
      - '**.sqlproj'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.sql'
      - '**.sqlproj'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build
      run: dotnet DatabaseProjectWingtips.sqlproj /p:RunSqlCodeAnalysis=true