name: Build SQL project with code analysis

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.sql'
      - '**.sqlproj'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.sql'
      - '**.sqlproj'

jobs:
  build:
    runs-on: windows-latest

    steps:

      
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Debug files
      run: |
          echo "Current working directory:"
          pwd
          echo "List all files:"
          ls -R
      
    - name: Build
      run: msbuild DatabaseProjectWingtips.sqlproj /p:RunSqlCodeAnalysis=true /t:Build